export const dataProjects= [
  {
    id:0,
    name:"hypecity",
    img:"img/dispositivos-hypecity.png",
    logo:"img/logo-hypecity.jpeg",
    gif:"img/gif-ecommerce.gif"
  },
  {
    id:1,
    name:"bybian",
    img:"img/dispositivos-bybian.png",
    logo:"img/logo-bybian.PNG",
    sections:[
      "img/screen-bybian/ilustracionesbybian.netlify.app_index.html.png",
      "img/screen-bybian/ilustracionesbybian.netlify.app_pag_nosotros.html.png",
      "img/screen-bybian/ilustracionesbybian.netlify.app_pag_servicios.html.png",
      "img/screen-bybian/ilustracionesbybian.netlify.app_pag_galeria.html.png",
      "img/screen-bybian/ilustracionesbybian.netlify.app_pag_contacto.html.png"
    ]
    
  },
  {
    id:2,
    name:"auri",
    img:"img/dispositivos-auri.png",
    logo:"img/logo-auri.png",
    sections:[
      "img/screen-bybian/www.transportesauri.com.png",
      "img/screen-bybian/www.transportesauri.com_nosotros.html.png",
  
    ]
  },
  {
    id:3,
    name:"sitioswebfm",
    img:"img/dispositivos-fm.png",
    logo:"https://sitioswebfm.netlify.app/img/logofm.png",
    sections:[
      "img/screen-bybian/sitioswebfm.netlify.app_.png"
    ]
  },
  {
    id:4,
    project:'test',
    name:"apihorario",
    img:"img/dispositivos-horario.png",
    logo:"img/logo-horario.png",
    gif:"img/gif-horario.gif"
  },
  {
    id:5,
    project:'test',
    name:"apiclima",
    img:"img/dispositivos-clima.png",
    logo:"img/logo-clima.png",
    gif:"img/gif-clima.gif"
  }
 
]